# Generated by Django 5.1.1 on 2024-10-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionpost',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
